[Sun Jan 12 00:11:47.206493 2020] [ssl:warn] [pid 36680:tid 500] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jan 12 00:11:47.271320 2020] [ssl:warn] [pid 36680:tid 500] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jan 12 00:11:47.271320 2020] [mpm_winnt:notice] [pid 36680:tid 500] AH00455: Apache/2.4.41 (Win64) OpenSSL/1.1.1c configured -- resuming normal operations
[Sun Jan 12 00:11:47.271320 2020] [mpm_winnt:notice] [pid 36680:tid 500] AH00456: Server built: Aug 10 2019 13:33:27
[Sun Jan 12 00:11:47.271320 2020] [core:notice] [pid 36680:tid 500] AH00094: Command line: 'E:\\clhcmdb\\Apache24\\bin\\httpd.exe -d E:/clhcmdb/Apache24'
[Sun Jan 12 00:11:47.273316 2020] [mpm_winnt:notice] [pid 36680:tid 500] AH00418: Parent: Created child process 9100
[Sun Jan 12 00:11:47.716130 2020] [ssl:warn] [pid 9100:tid 528] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jan 12 00:11:47.758046 2020] [ssl:warn] [pid 9100:tid 528] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jan 12 00:11:47.761010 2020] [mpm_winnt:notice] [pid 9100:tid 528] AH00354: Child: Starting 64 worker threads.
[Sun Jan 12 10:19:31.971608 2020] [mpm_winnt:notice] [pid 36680:tid 500] AH00422: Parent: Received shutdown signal -- Shutting down the server.
[Sun Jan 12 10:19:33.974212 2020] [mpm_winnt:notice] [pid 9100:tid 528] AH00364: Child: All worker threads have exited.
[Sun Jan 12 10:19:34.023999 2020] [mpm_winnt:notice] [pid 36680:tid 500] AH00430: Parent: Child process 9100 exited successfully.
Starting the 'apache2.4' service
[Sun Jan 12 11:33:20.379909 2020] [mpm_winnt:crit] [pid 39156:tid 656] (OS 2)系统找不到指定的文件。  : AH00378: Failed to start the 'apache2.4' service
[Sun Jan 12 11:42:42.283703 2020] [ssl:warn] [pid 8580:tid 684] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jan 12 11:42:42.364511 2020] [ssl:warn] [pid 8580:tid 684] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jan 12 11:42:42.364511 2020] [mpm_winnt:notice] [pid 8580:tid 684] AH00455: Apache/2.4.41 (Win64) OpenSSL/1.1.1c mod_wsgi/4.7.0 Python/3.6 configured -- resuming normal operations
[Sun Jan 12 11:42:42.376513 2020] [mpm_winnt:notice] [pid 8580:tid 684] AH00456: Server built: Aug 10 2019 13:33:27
[Sun Jan 12 11:42:42.376513 2020] [core:notice] [pid 8580:tid 684] AH00094: Command line: 'E:\\GitHub\\Apache24\\bin\\httpd.exe -d E:/GitHub/Apache24'
[Sun Jan 12 11:42:42.395399 2020] [mpm_winnt:notice] [pid 8580:tid 684] AH00418: Parent: Created child process 34012
[Sun Jan 12 11:42:42.840158 2020] [ssl:warn] [pid 34012:tid 572] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jan 12 11:42:42.893000 2020] [ssl:warn] [pid 34012:tid 572] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jan 12 11:42:42.945858 2020] [mpm_winnt:notice] [pid 34012:tid 572] AH00354: Child: Starting 64 worker threads.
[Sun Jan 12 11:42:53.078567 2020] [wsgi:error] [pid 34012:tid 1304] [client 127.0.0.1:1859] mod_wsgi (pid=34012): Failed to exec Python script file 'E:/GitHub/clhcmdb/clhcmdb/wsgi.py'.
[Sun Jan 12 11:42:53.079594 2020] [wsgi:error] [pid 34012:tid 1304] [client 127.0.0.1:1859] mod_wsgi (pid=34012): Exception occurred processing WSGI script 'E:/GitHub/clhcmdb/clhcmdb/wsgi.py'.
[Sun Jan 12 11:42:53.083554 2020] [wsgi:error] [pid 34012:tid 1304] [client 127.0.0.1:1859] Traceback (most recent call last):\r
[Sun Jan 12 11:42:53.083554 2020] [wsgi:error] [pid 34012:tid 1304] [client 127.0.0.1:1859]   File "E:/GitHub/clhcmdb/clhcmdb/wsgi.py", line 16, in <module>\r
[Sun Jan 12 11:42:53.083554 2020] [wsgi:error] [pid 34012:tid 1304] [client 127.0.0.1:1859]     application = get_wsgi_application()\r
[Sun Jan 12 11:42:53.083554 2020] [wsgi:error] [pid 34012:tid 1304] [client 127.0.0.1:1859]   File "c:\\users\\lee\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\django\\core\\wsgi.py", line 12, in get_wsgi_application\r
[Sun Jan 12 11:42:53.083554 2020] [wsgi:error] [pid 34012:tid 1304] [client 127.0.0.1:1859]     django.setup(set_prefix=False)\r
[Sun Jan 12 11:42:53.083554 2020] [wsgi:error] [pid 34012:tid 1304] [client 127.0.0.1:1859]   File "c:\\users\\lee\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\django\\__init__.py", line 24, in setup\r
[Sun Jan 12 11:42:53.083554 2020] [wsgi:error] [pid 34012:tid 1304] [client 127.0.0.1:1859]     apps.populate(settings.INSTALLED_APPS)\r
[Sun Jan 12 11:42:53.083554 2020] [wsgi:error] [pid 34012:tid 1304] [client 127.0.0.1:1859]   File "c:\\users\\lee\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\django\\apps\\registry.py", line 91, in populate\r
[Sun Jan 12 11:42:53.083554 2020] [wsgi:error] [pid 34012:tid 1304] [client 127.0.0.1:1859]     app_config = AppConfig.create(entry)\r
[Sun Jan 12 11:42:53.083554 2020] [wsgi:error] [pid 34012:tid 1304] [client 127.0.0.1:1859]   File "c:\\users\\lee\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\django\\apps\\config.py", line 90, in create\r
[Sun Jan 12 11:42:53.083554 2020] [wsgi:error] [pid 34012:tid 1304] [client 127.0.0.1:1859]     module = import_module(entry)\r
[Sun Jan 12 11:42:53.083554 2020] [wsgi:error] [pid 34012:tid 1304] [client 127.0.0.1:1859]   File "c:\\users\\lee\\appdata\\local\\programs\\python\\python36\\lib\\importlib\\__init__.py", line 126, in import_module\r
[Sun Jan 12 11:42:53.083554 2020] [wsgi:error] [pid 34012:tid 1304] [client 127.0.0.1:1859]     return _bootstrap._gcd_import(name[level:], package, level)\r
[Sun Jan 12 11:42:53.083554 2020] [wsgi:error] [pid 34012:tid 1304] [client 127.0.0.1:1859]   File "<frozen importlib._bootstrap>", line 994, in _gcd_import\r
[Sun Jan 12 11:42:53.083554 2020] [wsgi:error] [pid 34012:tid 1304] [client 127.0.0.1:1859]   File "<frozen importlib._bootstrap>", line 971, in _find_and_load\r
[Sun Jan 12 11:42:53.083554 2020] [wsgi:error] [pid 34012:tid 1304] [client 127.0.0.1:1859]   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked\r
[Sun Jan 12 11:42:53.083554 2020] [wsgi:error] [pid 34012:tid 1304] [client 127.0.0.1:1859] ModuleNotFoundError: No module named 'simpleui'\r
[Sun Jan 12 11:43:45.537839 2020] [wsgi:error] [pid 34012:tid 1304] [client 127.0.0.1:1926] mod_wsgi (pid=34012): Failed to exec Python script file 'E:/GitHub/clhcmdb/clhcmdb/wsgi.py'.
[Sun Jan 12 11:43:45.537839 2020] [wsgi:error] [pid 34012:tid 1304] [client 127.0.0.1:1926] mod_wsgi (pid=34012): Exception occurred processing WSGI script 'E:/GitHub/clhcmdb/clhcmdb/wsgi.py'.
[Sun Jan 12 11:43:45.537839 2020] [wsgi:error] [pid 34012:tid 1304] [client 127.0.0.1:1926] Traceback (most recent call last):\r
[Sun Jan 12 11:43:45.537839 2020] [wsgi:error] [pid 34012:tid 1304] [client 127.0.0.1:1926]   File "E:/GitHub/clhcmdb/clhcmdb/wsgi.py", line 16, in <module>\r
[Sun Jan 12 11:43:45.537839 2020] [wsgi:error] [pid 34012:tid 1304] [client 127.0.0.1:1926]     application = get_wsgi_application()\r
[Sun Jan 12 11:43:45.537839 2020] [wsgi:error] [pid 34012:tid 1304] [client 127.0.0.1:1926]   File "c:\\users\\lee\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\django\\core\\wsgi.py", line 12, in get_wsgi_application\r
[Sun Jan 12 11:43:45.537839 2020] [wsgi:error] [pid 34012:tid 1304] [client 127.0.0.1:1926]     django.setup(set_prefix=False)\r
[Sun Jan 12 11:43:45.537839 2020] [wsgi:error] [pid 34012:tid 1304] [client 127.0.0.1:1926]   File "c:\\users\\lee\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\django\\__init__.py", line 24, in setup\r
[Sun Jan 12 11:43:45.537839 2020] [wsgi:error] [pid 34012:tid 1304] [client 127.0.0.1:1926]     apps.populate(settings.INSTALLED_APPS)\r
[Sun Jan 12 11:43:45.537839 2020] [wsgi:error] [pid 34012:tid 1304] [client 127.0.0.1:1926]   File "c:\\users\\lee\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\django\\apps\\registry.py", line 83, in populate\r
[Sun Jan 12 11:43:45.537839 2020] [wsgi:error] [pid 34012:tid 1304] [client 127.0.0.1:1926]     raise RuntimeError("populate() isn't reentrant")\r
[Sun Jan 12 11:43:45.537839 2020] [wsgi:error] [pid 34012:tid 1304] [client 127.0.0.1:1926] RuntimeError: populate() isn't reentrant\r
[Sun Jan 12 11:43:51.480828 2020] [mpm_winnt:notice] [pid 8580:tid 684] AH00424: Parent: Received restart signal -- Restarting the server.
[Sun Jan 12 11:43:51.548674 2020] [ssl:warn] [pid 8580:tid 684] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jan 12 11:43:51.548674 2020] [mpm_winnt:notice] [pid 8580:tid 684] AH00455: Apache/2.4.41 (Win64) OpenSSL/1.1.1c mod_wsgi/4.7.0 Python/3.6 configured -- resuming normal operations
[Sun Jan 12 11:43:51.548674 2020] [mpm_winnt:notice] [pid 8580:tid 684] AH00456: Server built: Aug 10 2019 13:33:27
[Sun Jan 12 11:43:51.548674 2020] [core:notice] [pid 8580:tid 684] AH00094: Command line: 'E:\\GitHub\\Apache24\\bin\\httpd.exe -d E:/GitHub/Apache24'
[Sun Jan 12 11:43:51.549672 2020] [mpm_winnt:notice] [pid 8580:tid 684] AH00418: Parent: Created child process 16792
[Sun Jan 12 11:43:51.985991 2020] [ssl:warn] [pid 16792:tid 680] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jan 12 11:43:52.026044 2020] [ssl:warn] [pid 16792:tid 680] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jan 12 11:43:52.482317 2020] [mpm_winnt:notice] [pid 16792:tid 680] AH00354: Child: Starting 64 worker threads.
[Sun Jan 12 11:43:53.483739 2020] [mpm_winnt:notice] [pid 34012:tid 572] AH00364: Child: All worker threads have exited.
[Sun Jan 12 11:43:57.587184 2020] [wsgi:error] [pid 16792:tid 1324] [client 127.0.0.1:1942] mod_wsgi (pid=16792): Failed to exec Python script file 'E:/GitHub/clhcmdb/clhcmdb/wsgi.py'.
[Sun Jan 12 11:43:57.587184 2020] [wsgi:error] [pid 16792:tid 1324] [client 127.0.0.1:1942] mod_wsgi (pid=16792): Exception occurred processing WSGI script 'E:/GitHub/clhcmdb/clhcmdb/wsgi.py'.
[Sun Jan 12 11:43:57.588181 2020] [wsgi:error] [pid 16792:tid 1324] [client 127.0.0.1:1942] Traceback (most recent call last):\r
[Sun Jan 12 11:43:57.589177 2020] [wsgi:error] [pid 16792:tid 1324] [client 127.0.0.1:1942]   File "E:/GitHub/clhcmdb/clhcmdb/wsgi.py", line 16, in <module>\r
[Sun Jan 12 11:43:57.589177 2020] [wsgi:error] [pid 16792:tid 1324] [client 127.0.0.1:1942]     application = get_wsgi_application()\r
[Sun Jan 12 11:43:57.589177 2020] [wsgi:error] [pid 16792:tid 1324] [client 127.0.0.1:1942]   File "c:\\users\\lee\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\django\\core\\wsgi.py", line 12, in get_wsgi_application\r
[Sun Jan 12 11:43:57.589177 2020] [wsgi:error] [pid 16792:tid 1324] [client 127.0.0.1:1942]     django.setup(set_prefix=False)\r
[Sun Jan 12 11:43:57.589177 2020] [wsgi:error] [pid 16792:tid 1324] [client 127.0.0.1:1942]   File "c:\\users\\lee\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\django\\__init__.py", line 24, in setup\r
[Sun Jan 12 11:43:57.589177 2020] [wsgi:error] [pid 16792:tid 1324] [client 127.0.0.1:1942]     apps.populate(settings.INSTALLED_APPS)\r
[Sun Jan 12 11:43:57.589177 2020] [wsgi:error] [pid 16792:tid 1324] [client 127.0.0.1:1942]   File "c:\\users\\lee\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\django\\apps\\registry.py", line 91, in populate\r
[Sun Jan 12 11:43:57.589177 2020] [wsgi:error] [pid 16792:tid 1324] [client 127.0.0.1:1942]     app_config = AppConfig.create(entry)\r
[Sun Jan 12 11:43:57.589177 2020] [wsgi:error] [pid 16792:tid 1324] [client 127.0.0.1:1942]   File "c:\\users\\lee\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\django\\apps\\config.py", line 90, in create\r
[Sun Jan 12 11:43:57.589177 2020] [wsgi:error] [pid 16792:tid 1324] [client 127.0.0.1:1942]     module = import_module(entry)\r
[Sun Jan 12 11:43:57.589177 2020] [wsgi:error] [pid 16792:tid 1324] [client 127.0.0.1:1942]   File "c:\\users\\lee\\appdata\\local\\programs\\python\\python36\\lib\\importlib\\__init__.py", line 126, in import_module\r
[Sun Jan 12 11:43:57.589177 2020] [wsgi:error] [pid 16792:tid 1324] [client 127.0.0.1:1942]     return _bootstrap._gcd_import(name[level:], package, level)\r
[Sun Jan 12 11:43:57.589177 2020] [wsgi:error] [pid 16792:tid 1324] [client 127.0.0.1:1942]   File "<frozen importlib._bootstrap>", line 994, in _gcd_import\r
[Sun Jan 12 11:43:57.589177 2020] [wsgi:error] [pid 16792:tid 1324] [client 127.0.0.1:1942]   File "<frozen importlib._bootstrap>", line 971, in _find_and_load\r
[Sun Jan 12 11:43:57.589177 2020] [wsgi:error] [pid 16792:tid 1324] [client 127.0.0.1:1942]   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked\r
[Sun Jan 12 11:43:57.589177 2020] [wsgi:error] [pid 16792:tid 1324] [client 127.0.0.1:1942] ModuleNotFoundError: No module named 'simpleui'\r
[Sun Jan 12 11:45:13.767831 2020] [wsgi:error] [pid 16792:tid 1324] [client 127.0.0.1:2029] mod_wsgi (pid=16792): Failed to exec Python script file 'E:/GitHub/clhcmdb/clhcmdb/wsgi.py'.
[Sun Jan 12 11:45:13.768805 2020] [wsgi:error] [pid 16792:tid 1324] [client 127.0.0.1:2029] mod_wsgi (pid=16792): Exception occurred processing WSGI script 'E:/GitHub/clhcmdb/clhcmdb/wsgi.py'.
[Sun Jan 12 11:45:13.769802 2020] [wsgi:error] [pid 16792:tid 1324] [client 127.0.0.1:2029] Traceback (most recent call last):\r
[Sun Jan 12 11:45:13.769802 2020] [wsgi:error] [pid 16792:tid 1324] [client 127.0.0.1:2029]   File "E:/GitHub/clhcmdb/clhcmdb/wsgi.py", line 16, in <module>\r
[Sun Jan 12 11:45:13.769802 2020] [wsgi:error] [pid 16792:tid 1324] [client 127.0.0.1:2029]     application = get_wsgi_application()\r
[Sun Jan 12 11:45:13.769802 2020] [wsgi:error] [pid 16792:tid 1324] [client 127.0.0.1:2029]   File "c:\\users\\lee\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\django\\core\\wsgi.py", line 12, in get_wsgi_application\r
[Sun Jan 12 11:45:13.769802 2020] [wsgi:error] [pid 16792:tid 1324] [client 127.0.0.1:2029]     django.setup(set_prefix=False)\r
[Sun Jan 12 11:45:13.769802 2020] [wsgi:error] [pid 16792:tid 1324] [client 127.0.0.1:2029]   File "c:\\users\\lee\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\django\\__init__.py", line 24, in setup\r
[Sun Jan 12 11:45:13.769802 2020] [wsgi:error] [pid 16792:tid 1324] [client 127.0.0.1:2029]     apps.populate(settings.INSTALLED_APPS)\r
[Sun Jan 12 11:45:13.769802 2020] [wsgi:error] [pid 16792:tid 1324] [client 127.0.0.1:2029]   File "c:\\users\\lee\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\django\\apps\\registry.py", line 83, in populate\r
[Sun Jan 12 11:45:13.769802 2020] [wsgi:error] [pid 16792:tid 1324] [client 127.0.0.1:2029]     raise RuntimeError("populate() isn't reentrant")\r
[Sun Jan 12 11:45:13.769802 2020] [wsgi:error] [pid 16792:tid 1324] [client 127.0.0.1:2029] RuntimeError: populate() isn't reentrant\r
[Sun Jan 12 12:37:03.102694 2020] [wsgi:error] [pid 16792:tid 1324] [client 127.0.0.1:1249] mod_wsgi (pid=16792): Failed to exec Python script file 'E:/GitHub/clhcmdb/clhcmdb/wsgi.py'.
[Sun Jan 12 12:37:03.103667 2020] [wsgi:error] [pid 16792:tid 1324] [client 127.0.0.1:1249] mod_wsgi (pid=16792): Exception occurred processing WSGI script 'E:/GitHub/clhcmdb/clhcmdb/wsgi.py'.
[Sun Jan 12 12:37:03.103667 2020] [wsgi:error] [pid 16792:tid 1324] [client 127.0.0.1:1249] Traceback (most recent call last):\r
[Sun Jan 12 12:37:03.103667 2020] [wsgi:error] [pid 16792:tid 1324] [client 127.0.0.1:1249]   File "E:/GitHub/clhcmdb/clhcmdb/wsgi.py", line 16, in <module>\r
[Sun Jan 12 12:37:03.103667 2020] [wsgi:error] [pid 16792:tid 1324] [client 127.0.0.1:1249]     application = get_wsgi_application()\r
[Sun Jan 12 12:37:03.103667 2020] [wsgi:error] [pid 16792:tid 1324] [client 127.0.0.1:1249]   File "c:\\users\\lee\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\django\\core\\wsgi.py", line 12, in get_wsgi_application\r
[Sun Jan 12 12:37:03.103667 2020] [wsgi:error] [pid 16792:tid 1324] [client 127.0.0.1:1249]     django.setup(set_prefix=False)\r
[Sun Jan 12 12:37:03.103667 2020] [wsgi:error] [pid 16792:tid 1324] [client 127.0.0.1:1249]   File "c:\\users\\lee\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\django\\__init__.py", line 24, in setup\r
[Sun Jan 12 12:37:03.103667 2020] [wsgi:error] [pid 16792:tid 1324] [client 127.0.0.1:1249]     apps.populate(settings.INSTALLED_APPS)\r
[Sun Jan 12 12:37:03.103667 2020] [wsgi:error] [pid 16792:tid 1324] [client 127.0.0.1:1249]   File "c:\\users\\lee\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\django\\apps\\registry.py", line 83, in populate\r
[Sun Jan 12 12:37:03.103667 2020] [wsgi:error] [pid 16792:tid 1324] [client 127.0.0.1:1249]     raise RuntimeError("populate() isn't reentrant")\r
[Sun Jan 12 12:37:03.103667 2020] [wsgi:error] [pid 16792:tid 1324] [client 127.0.0.1:1249] RuntimeError: populate() isn't reentrant\r
[Sun Jan 12 12:38:51.863038 2020] [mpm_winnt:notice] [pid 8580:tid 684] AH00424: Parent: Received restart signal -- Restarting the server.
(OS 10048)通常每个套接字地址(协议/网络地址/端口)只允许使用一次。  : AH00072: make_sock: could not bind to address 127.0.0.1:80
AH00451: no listening sockets available, shutting down
[Sun Jan 12 12:38:52.154259 2020] [:emerg] [pid 8580:tid 684] AH00019: Unable to open logs, exiting
[Sun Jan 12 12:38:53.864453 2020] [mpm_winnt:notice] [pid 16792:tid 680] AH00364: Child: All worker threads have exited.
Starting the 'apache2.4' service
The 'apache2.4' service is running.
sl:warn] [pid 36652:tid 668] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jan 12 12:40:20.888251 2020] [core:warn] [pid 36652:tid 668] AH00098: pid file E:/GitHub/Apache24/logs/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
[Sun Jan 12 12:40:20.890246 2020] [ssl:warn] [pid 36652:tid 668] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jan 12 12:40:20.891243 2020] [mpm_winnt:notice] [pid 36652:tid 668] AH00455: Apache/2.4.41 (Win64) OpenSSL/1.1.1c mod_wsgi/4.7.0 Python/3.6 configured -- resuming normal operations
[Sun Jan 12 12:40:20.891243 2020] [mpm_winnt:notice] [pid 36652:tid 668] AH00456: Server built: Aug 10 2019 13:33:27
[Sun Jan 12 12:40:20.891243 2020] [core:notice] [pid 36652:tid 668] AH00094: Command line: 'E:\\GitHub\\Apache24\\bin\\httpd.exe -d E:/GitHub/Apache24'
[Sun Jan 12 12:40:20.892241 2020] [mpm_winnt:notice] [pid 36652:tid 668] AH00418: Parent: Created child process 22504
[Sun Jan 12 12:40:21.334059 2020] [ssl:warn] [pid 22504:tid 528] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jan 12 12:40:21.379964 2020] [ssl:warn] [pid 22504:tid 528] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jan 12 12:40:21.451771 2020] [mpm_winnt:notice] [pid 22504:tid 528] AH00354: Child: Starting 64 worker threads.
[Sun Jan 12 12:40:35.494195 2020] [wsgi:error] [pid 22504:tid 1276] [client 127.0.0.1:6091] mod_wsgi (pid=22504): Failed to exec Python script file 'E:/GitHub/clhcmdb/clhcmdb/wsgi.py'.
[Sun Jan 12 12:40:35.494195 2020] [wsgi:error] [pid 22504:tid 1276] [client 127.0.0.1:6091] mod_wsgi (pid=22504): Exception occurred processing WSGI script 'E:/GitHub/clhcmdb/clhcmdb/wsgi.py'.
[Sun Jan 12 12:40:35.498184 2020] [wsgi:error] [pid 22504:tid 1276] [client 127.0.0.1:6091] Traceback (most recent call last):\r
[Sun Jan 12 12:40:35.498184 2020] [wsgi:error] [pid 22504:tid 1276] [client 127.0.0.1:6091]   File "E:/GitHub/clhcmdb/clhcmdb/wsgi.py", line 16, in <module>\r
[Sun Jan 12 12:40:35.498184 2020] [wsgi:error] [pid 22504:tid 1276] [client 127.0.0.1:6091]     application = get_wsgi_application()\r
[Sun Jan 12 12:40:35.498184 2020] [wsgi:error] [pid 22504:tid 1276] [client 127.0.0.1:6091]   File "c:\\users\\lee\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\django\\core\\wsgi.py", line 12, in get_wsgi_application\r
[Sun Jan 12 12:40:35.499181 2020] [wsgi:error] [pid 22504:tid 1276] [client 127.0.0.1:6091]     django.setup(set_prefix=False)\r
[Sun Jan 12 12:40:35.499181 2020] [wsgi:error] [pid 22504:tid 1276] [client 127.0.0.1:6091]   File "c:\\users\\lee\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\django\\__init__.py", line 24, in setup\r
[Sun Jan 12 12:40:35.499181 2020] [wsgi:error] [pid 22504:tid 1276] [client 127.0.0.1:6091]     apps.populate(settings.INSTALLED_APPS)\r
[Sun Jan 12 12:40:35.499181 2020] [wsgi:error] [pid 22504:tid 1276] [client 127.0.0.1:6091]   File "c:\\users\\lee\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\django\\apps\\registry.py", line 91, in populate\r
[Sun Jan 12 12:40:35.499181 2020] [wsgi:error] [pid 22504:tid 1276] [client 127.0.0.1:6091]     app_config = AppConfig.create(entry)\r
[Sun Jan 12 12:40:35.499181 2020] [wsgi:error] [pid 22504:tid 1276] [client 127.0.0.1:6091]   File "c:\\users\\lee\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\django\\apps\\config.py", line 90, in create\r
[Sun Jan 12 12:40:35.499181 2020] [wsgi:error] [pid 22504:tid 1276] [client 127.0.0.1:6091]     module = import_module(entry)\r
[Sun Jan 12 12:40:35.499181 2020] [wsgi:error] [pid 22504:tid 1276] [client 127.0.0.1:6091]   File "c:\\users\\lee\\appdata\\local\\programs\\python\\python36\\lib\\importlib\\__init__.py", line 126, in import_module\r
[Sun Jan 12 12:40:35.499181 2020] [wsgi:error] [pid 22504:tid 1276] [client 127.0.0.1:6091]     return _bootstrap._gcd_import(name[level:], package, level)\r
[Sun Jan 12 12:40:35.499181 2020] [wsgi:error] [pid 22504:tid 1276] [client 127.0.0.1:6091]   File "<frozen importlib._bootstrap>", line 994, in _gcd_import\r
[Sun Jan 12 12:40:35.499181 2020] [wsgi:error] [pid 22504:tid 1276] [client 127.0.0.1:6091]   File "<frozen importlib._bootstrap>", line 971, in _find_and_load\r
[Sun Jan 12 12:40:35.499181 2020] [wsgi:error] [pid 22504:tid 1276] [client 127.0.0.1:6091]   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked\r
[Sun Jan 12 12:40:35.499181 2020] [wsgi:error] [pid 22504:tid 1276] [client 127.0.0.1:6091] ModuleNotFoundError: No module named 'simpleui'\r
[Sun Jan 12 12:40:35.566006 2020] [wsgi:error] [pid 22504:tid 1276] [client 127.0.0.1:6105] mod_wsgi (pid=22504): Failed to exec Python script file 'E:/GitHub/clhcmdb/clhcmdb/wsgi.py'.
[Sun Jan 12 12:40:35.566006 2020] [wsgi:error] [pid 22504:tid 1276] [client 127.0.0.1:6105] mod_wsgi (pid=22504): Exception occurred processing WSGI script 'E:/GitHub/clhcmdb/clhcmdb/wsgi.py'.
[Sun Jan 12 12:40:35.567001 2020] [wsgi:error] [pid 22504:tid 1276] [client 127.0.0.1:6105] Traceback (most recent call last):\r
[Sun Jan 12 12:40:35.567001 2020] [wsgi:error] [pid 22504:tid 1276] [client 127.0.0.1:6105]   File "E:/GitHub/clhcmdb/clhcmdb/wsgi.py", line 16, in <module>\r
[Sun Jan 12 12:40:35.567001 2020] [wsgi:error] [pid 22504:tid 1276] [client 127.0.0.1:6105]     application = get_wsgi_application()\r
[Sun Jan 12 12:40:35.567001 2020] [wsgi:error] [pid 22504:tid 1276] [client 127.0.0.1:6105]   File "c:\\users\\lee\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\django\\core\\wsgi.py", line 12, in get_wsgi_application\r
[Sun Jan 12 12:40:35.567001 2020] [wsgi:error] [pid 22504:tid 1276] [client 127.0.0.1:6105]     django.setup(set_prefix=False)\r
[Sun Jan 12 12:40:35.567001 2020] [wsgi:error] [pid 22504:tid 1276] [client 127.0.0.1:6105]   File "c:\\users\\lee\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\django\\__init__.py", line 24, in setup\r
[Sun Jan 12 12:40:35.567001 2020] [wsgi:error] [pid 22504:tid 1276] [client 127.0.0.1:6105]     apps.populate(settings.INSTALLED_APPS)\r
[Sun Jan 12 12:40:35.567001 2020] [wsgi:error] [pid 22504:tid 1276] [client 127.0.0.1:6105]   File "c:\\users\\lee\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\django\\apps\\registry.py", line 83, in populate\r
[Sun Jan 12 12:40:35.567001 2020] [wsgi:error] [pid 22504:tid 1276] [client 127.0.0.1:6105]     raise RuntimeError("populate() isn't reentrant")\r
[Sun Jan 12 12:40:35.567001 2020] [wsgi:error] [pid 22504:tid 1276] [client 127.0.0.1:6105] RuntimeError: populate() isn't reentrant\r
[Sun Jan 12 12:45:13.971310 2020] [wsgi:error] [pid 22504:tid 1276] [client 127.0.0.1:12359] mod_wsgi (pid=22504): Failed to exec Python script file 'E:/GitHub/clhcmdb/clhcmdb/wsgi.py'.
[Sun Jan 12 12:45:13.971310 2020] [wsgi:error] [pid 22504:tid 1276] [client 127.0.0.1:12359] mod_wsgi (pid=22504): Exception occurred processing WSGI script 'E:/GitHub/clhcmdb/clhcmdb/wsgi.py'.
[Sun Jan 12 12:45:13.971310 2020] [wsgi:error] [pid 22504:tid 1276] [client 127.0.0.1:12359] Traceback (most recent call last):\r
[Sun Jan 12 12:45:13.971310 2020] [wsgi:error] [pid 22504:tid 1276] [client 127.0.0.1:12359]   File "E:/GitHub/clhcmdb/clhcmdb/wsgi.py", line 16, in <module>\r
[Sun Jan 12 12:45:13.971310 2020] [wsgi:error] [pid 22504:tid 1276] [client 127.0.0.1:12359]     application = get_wsgi_application()\r
[Sun Jan 12 12:45:13.971310 2020] [wsgi:error] [pid 22504:tid 1276] [client 127.0.0.1:12359]   File "c:\\users\\lee\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\django\\core\\wsgi.py", line 12, in get_wsgi_application\r
[Sun Jan 12 12:45:13.971310 2020] [wsgi:error] [pid 22504:tid 1276] [client 127.0.0.1:12359]     django.setup(set_prefix=False)\r
[Sun Jan 12 12:45:13.971310 2020] [wsgi:error] [pid 22504:tid 1276] [client 127.0.0.1:12359]   File "c:\\users\\lee\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\django\\__init__.py", line 24, in setup\r
[Sun Jan 12 12:45:13.971310 2020] [wsgi:error] [pid 22504:tid 1276] [client 127.0.0.1:12359]     apps.populate(settings.INSTALLED_APPS)\r
[Sun Jan 12 12:45:13.971310 2020] [wsgi:error] [pid 22504:tid 1276] [client 127.0.0.1:12359]   File "c:\\users\\lee\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\django\\apps\\registry.py", line 83, in populate\r
[Sun Jan 12 12:45:13.971310 2020] [wsgi:error] [pid 22504:tid 1276] [client 127.0.0.1:12359]     raise RuntimeError("populate() isn't reentrant")\r
[Sun Jan 12 12:45:13.971310 2020] [wsgi:error] [pid 22504:tid 1276] [client 127.0.0.1:12359] RuntimeError: populate() isn't reentrant\r
[Sun Jan 12 12:45:28.049769 2020] [wsgi:error] [pid 22504:tid 1276] [client 127.0.0.1:12676] mod_wsgi (pid=22504): Failed to exec Python script file 'E:/GitHub/clhcmdb/clhcmdb/wsgi.py'.
[Sun Jan 12 12:45:28.049769 2020] [wsgi:error] [pid 22504:tid 1276] [client 127.0.0.1:12676] mod_wsgi (pid=22504): Exception occurred processing WSGI script 'E:/GitHub/clhcmdb/clhcmdb/wsgi.py'.
[Sun Jan 12 12:45:28.049769 2020] [wsgi:error] [pid 22504:tid 1276] [client 127.0.0.1:12676] Traceback (most recent call last):\r
[Sun Jan 12 12:45:28.049769 2020] [wsgi:error] [pid 22504:tid 1276] [client 127.0.0.1:12676]   File "E:/GitHub/clhcmdb/clhcmdb/wsgi.py", line 16, in <module>\r
[Sun Jan 12 12:45:28.049769 2020] [wsgi:error] [pid 22504:tid 1276] [client 127.0.0.1:12676]     application = get_wsgi_application()\r
[Sun Jan 12 12:45:28.049769 2020] [wsgi:error] [pid 22504:tid 1276] [client 127.0.0.1:12676]   File "c:\\users\\lee\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\django\\core\\wsgi.py", line 12, in get_wsgi_application\r
[Sun Jan 12 12:45:28.049769 2020] [wsgi:error] [pid 22504:tid 1276] [client 127.0.0.1:12676]     django.setup(set_prefix=False)\r
[Sun Jan 12 12:45:28.049769 2020] [wsgi:error] [pid 22504:tid 1276] [client 127.0.0.1:12676]   File "c:\\users\\lee\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\django\\__init__.py", line 24, in setup\r
[Sun Jan 12 12:45:28.049769 2020] [wsgi:error] [pid 22504:tid 1276] [client 127.0.0.1:12676]     apps.populate(settings.INSTALLED_APPS)\r
[Sun Jan 12 12:45:28.049769 2020] [wsgi:error] [pid 22504:tid 1276] [client 127.0.0.1:12676]   File "c:\\users\\lee\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\django\\apps\\registry.py", line 83, in populate\r
[Sun Jan 12 12:45:28.049769 2020] [wsgi:error] [pid 22504:tid 1276] [client 127.0.0.1:12676]     raise RuntimeError("populate() isn't reentrant")\r
[Sun Jan 12 12:45:28.049769 2020] [wsgi:error] [pid 22504:tid 1276] [client 127.0.0.1:12676] RuntimeError: populate() isn't reentrant\r
[Sun Jan 12 12:45:30.680734 2020] [wsgi:error] [pid 22504:tid 1276] [client 127.0.0.1:12731] mod_wsgi (pid=22504): Failed to exec Python script file 'E:/GitHub/clhcmdb/clhcmdb/wsgi.py'.
[Sun Jan 12 12:45:30.680734 2020] [wsgi:error] [pid 22504:tid 1276] [client 127.0.0.1:12731] mod_wsgi (pid=22504): Exception occurred processing WSGI script 'E:/GitHub/clhcmdb/clhcmdb/wsgi.py'.
[Sun Jan 12 12:45:30.680734 2020] [wsgi:error] [pid 22504:tid 1276] [client 127.0.0.1:12731] Traceback (most recent call last):\r
[Sun Jan 12 12:45:30.680734 2020] [wsgi:error] [pid 22504:tid 1276] [client 127.0.0.1:12731]   File "E:/GitHub/clhcmdb/clhcmdb/wsgi.py", line 16, in <module>\r
[Sun Jan 12 12:45:30.680734 2020] [wsgi:error] [pid 22504:tid 1276] [client 127.0.0.1:12731]     application = get_wsgi_application()\r
[Sun Jan 12 12:45:30.680734 2020] [wsgi:error] [pid 22504:tid 1276] [client 127.0.0.1:12731]   File "c:\\users\\lee\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\django\\core\\wsgi.py", line 12, in get_wsgi_application\r
[Sun Jan 12 12:45:30.680734 2020] [wsgi:error] [pid 22504:tid 1276] [client 127.0.0.1:12731]     django.setup(set_prefix=False)\r
[Sun Jan 12 12:45:30.680734 2020] [wsgi:error] [pid 22504:tid 1276] [client 127.0.0.1:12731]   File "c:\\users\\lee\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\django\\__init__.py", line 24, in setup\r
[Sun Jan 12 12:45:30.680734 2020] [wsgi:error] [pid 22504:tid 1276] [client 127.0.0.1:12731]     apps.populate(settings.INSTALLED_APPS)\r
[Sun Jan 12 12:45:30.680734 2020] [wsgi:error] [pid 22504:tid 1276] [client 127.0.0.1:12731]   File "c:\\users\\lee\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\django\\apps\\registry.py", line 83, in populate\r
[Sun Jan 12 12:45:30.680734 2020] [wsgi:error] [pid 22504:tid 1276] [client 127.0.0.1:12731]     raise RuntimeError("populate() isn't reentrant")\r
[Sun Jan 12 12:45:30.680734 2020] [wsgi:error] [pid 22504:tid 1276] [client 127.0.0.1:12731] RuntimeError: populate() isn't reentrant\r
[Sun Jan 12 12:48:00.166840 2020] [mpm_winnt:notice] [pid 36652:tid 668] AH00424: Parent: Received restart signal -- Restarting the server.
[Sun Jan 12 12:48:00.243634 2020] [ssl:warn] [pid 36652:tid 668] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jan 12 12:48:00.243634 2020] [mpm_winnt:notice] [pid 36652:tid 668] AH00455: Apache/2.4.41 (Win64) OpenSSL/1.1.1c mod_wsgi/4.7.0 Python/3.6 configured -- resuming normal operations
[Sun Jan 12 12:48:00.243634 2020] [mpm_winnt:notice] [pid 36652:tid 668] AH00456: Server built: Aug 10 2019 13:33:27
[Sun Jan 12 12:48:00.243634 2020] [core:notice] [pid 36652:tid 668] AH00094: Command line: 'E:\\GitHub\\Apache24\\bin\\httpd.exe -d E:/GitHub/Apache24'
[Sun Jan 12 12:48:00.245629 2020] [mpm_winnt:notice] [pid 36652:tid 668] AH00418: Parent: Created child process 35740
[Sun Jan 12 12:48:00.686481 2020] [ssl:warn] [pid 35740:tid 668] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jan 12 12:48:00.731330 2020] [ssl:warn] [pid 35740:tid 668] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jan 12 12:48:01.168244 2020] [mpm_winnt:notice] [pid 35740:tid 668] AH00354: Child: Starting 64 worker threads.
[Sun Jan 12 12:48:02.169489 2020] [mpm_winnt:notice] [pid 22504:tid 528] AH00364: Child: All worker threads have exited.
[Sun Jan 12 12:48:21.577587 2020] [wsgi:error] [pid 35740:tid 1324] [client 127.0.0.1:2554] mod_wsgi (pid=35740): Failed to exec Python script file 'E:/GitHub/clhcmdb/clhcmdb/wsgi.py'.
[Sun Jan 12 12:48:21.577587 2020] [wsgi:error] [pid 35740:tid 1324] [client 127.0.0.1:2554] mod_wsgi (pid=35740): Exception occurred processing WSGI script 'E:/GitHub/clhcmdb/clhcmdb/wsgi.py'.
[Sun Jan 12 12:48:21.579582 2020] [wsgi:error] [pid 35740:tid 1324] [client 127.0.0.1:2554] Traceback (most recent call last):\r
[Sun Jan 12 12:48:21.579582 2020] [wsgi:error] [pid 35740:tid 1324] [client 127.0.0.1:2554]   File "E:/GitHub/clhcmdb/clhcmdb/wsgi.py", line 16, in <module>\r
[Sun Jan 12 12:48:21.579582 2020] [wsgi:error] [pid 35740:tid 1324] [client 127.0.0.1:2554]     application = get_wsgi_application()\r
[Sun Jan 12 12:48:21.579582 2020] [wsgi:error] [pid 35740:tid 1324] [client 127.0.0.1:2554]   File "c:\\users\\lee\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\django\\core\\wsgi.py", line 12, in get_wsgi_application\r
[Sun Jan 12 12:48:21.579582 2020] [wsgi:error] [pid 35740:tid 1324] [client 127.0.0.1:2554]     django.setup(set_prefix=False)\r
[Sun Jan 12 12:48:21.579582 2020] [wsgi:error] [pid 35740:tid 1324] [client 127.0.0.1:2554]   File "c:\\users\\lee\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\django\\__init__.py", line 24, in setup\r
[Sun Jan 12 12:48:21.579582 2020] [wsgi:error] [pid 35740:tid 1324] [client 127.0.0.1:2554]     apps.populate(settings.INSTALLED_APPS)\r
[Sun Jan 12 12:48:21.579582 2020] [wsgi:error] [pid 35740:tid 1324] [client 127.0.0.1:2554]   File "c:\\users\\lee\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\django\\apps\\registry.py", line 91, in populate\r
[Sun Jan 12 12:48:21.579582 2020] [wsgi:error] [pid 35740:tid 1324] [client 127.0.0.1:2554]     app_config = AppConfig.create(entry)\r
[Sun Jan 12 12:48:21.579582 2020] [wsgi:error] [pid 35740:tid 1324] [client 127.0.0.1:2554]   File "c:\\users\\lee\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\django\\apps\\config.py", line 90, in create\r
[Sun Jan 12 12:48:21.579582 2020] [wsgi:error] [pid 35740:tid 1324] [client 127.0.0.1:2554]     module = import_module(entry)\r
[Sun Jan 12 12:48:21.579582 2020] [wsgi:error] [pid 35740:tid 1324] [client 127.0.0.1:2554]   File "c:\\users\\lee\\appdata\\local\\programs\\python\\python36\\lib\\importlib\\__init__.py", line 126, in import_module\r
[Sun Jan 12 12:48:21.579582 2020] [wsgi:error] [pid 35740:tid 1324] [client 127.0.0.1:2554]     return _bootstrap._gcd_import(name[level:], package, level)\r
[Sun Jan 12 12:48:21.579582 2020] [wsgi:error] [pid 35740:tid 1324] [client 127.0.0.1:2554]   File "<frozen importlib._bootstrap>", line 994, in _gcd_import\r
[Sun Jan 12 12:48:21.579582 2020] [wsgi:error] [pid 35740:tid 1324] [client 127.0.0.1:2554]   File "<frozen importlib._bootstrap>", line 971, in _find_and_load\r
[Sun Jan 12 12:48:21.579582 2020] [wsgi:error] [pid 35740:tid 1324] [client 127.0.0.1:2554]   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked\r
[Sun Jan 12 12:48:21.579582 2020] [wsgi:error] [pid 35740:tid 1324] [client 127.0.0.1:2554] ModuleNotFoundError: No module named 'simpleui'\r
[Sun Jan 12 12:53:35.032705 2020] [mpm_winnt:notice] [pid 36652:tid 668] AH00424: Parent: Received restart signal -- Restarting the server.
(OS 10048)通常每个套接字地址(协议/网络地址/端口)只允许使用一次。  : AH00072: make_sock: could not bind to address 127.0.0.1:80
AH00451: no listening sockets available, shutting down
[Sun Jan 12 12:53:35.044701 2020] [:emerg] [pid 36652:tid 668] AH00019: Unable to open logs, exiting
[Sun Jan 12 12:53:37.033391 2020] [mpm_winnt:notice] [pid 35740:tid 668] AH00364: Child: All worker threads have exited.
Starting the 'apache2.4' service
The 'apache2.4' service is running.
sl:warn] [pid 27784:tid 660] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jan 12 12:54:27.975294 2020] [core:warn] [pid 27784:tid 660] AH00098: pid file E:/GitHub/Apache24/logs/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
[Sun Jan 12 12:54:27.978286 2020] [ssl:warn] [pid 27784:tid 660] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jan 12 12:54:27.979284 2020] [mpm_winnt:notice] [pid 27784:tid 660] AH00455: Apache/2.4.41 (Win64) OpenSSL/1.1.1c configured -- resuming normal operations
[Sun Jan 12 12:54:27.979284 2020] [mpm_winnt:notice] [pid 27784:tid 660] AH00456: Server built: Aug 10 2019 13:33:27
[Sun Jan 12 12:54:27.979284 2020] [core:notice] [pid 27784:tid 660] AH00094: Command line: 'E:\\GitHub\\Apache24\\bin\\httpd.exe -d E:/GitHub/Apache24'
[Sun Jan 12 12:54:27.981279 2020] [mpm_winnt:notice] [pid 27784:tid 660] AH00418: Parent: Created child process 39128
[Sun Jan 12 12:54:28.396168 2020] [ssl:warn] [pid 39128:tid 584] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jan 12 12:54:28.439054 2020] [ssl:warn] [pid 39128:tid 584] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jan 12 12:54:28.442046 2020] [mpm_winnt:notice] [pid 39128:tid 584] AH00354: Child: Starting 64 worker threads.
[Sun Jan 12 12:57:13.399357 2020] [mpm_winnt:notice] [pid 27784:tid 660] AH00424: Parent: Received restart signal -- Restarting the server.
[Sun Jan 12 12:57:13.473159 2020] [ssl:warn] [pid 27784:tid 660] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jan 12 12:57:13.474157 2020] [mpm_winnt:notice] [pid 27784:tid 660] AH00455: Apache/2.4.41 (Win64) OpenSSL/1.1.1c mod_wsgi/4.7.0 Python/3.6 configured -- resuming normal operations
[Sun Jan 12 12:57:13.474157 2020] [mpm_winnt:notice] [pid 27784:tid 660] AH00456: Server built: Aug 10 2019 13:33:27
[Sun Jan 12 12:57:13.474157 2020] [core:notice] [pid 27784:tid 660] AH00094: Command line: 'E:\\GitHub\\Apache24\\bin\\httpd.exe -d E:/GitHub/Apache24'
[Sun Jan 12 12:57:13.475183 2020] [mpm_winnt:notice] [pid 27784:tid 660] AH00418: Parent: Created child process 38988
[Sun Jan 12 12:57:13.908996 2020] [ssl:warn] [pid 38988:tid 592] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jan 12 12:57:13.960883 2020] [ssl:warn] [pid 38988:tid 592] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jan 12 12:57:14.399690 2020] [mpm_winnt:notice] [pid 38988:tid 592] AH00354: Child: Starting 64 worker threads.
[Sun Jan 12 12:57:15.400038 2020] [mpm_winnt:notice] [pid 39128:tid 584] AH00364: Child: All worker threads have exited.
[Sun Jan 12 12:57:21.338130 2020] [wsgi:error] [pid 38988:tid 1324] [client 127.0.0.1:14622] mod_wsgi (pid=38988): Failed to exec Python script file 'E:/GitHub/clhcmdb/clhcmdb/wsgi.py'.
[Sun Jan 12 12:57:21.338130 2020] [wsgi:error] [pid 38988:tid 1324] [client 127.0.0.1:14622] mod_wsgi (pid=38988): Exception occurred processing WSGI script 'E:/GitHub/clhcmdb/clhcmdb/wsgi.py'.
[Sun Jan 12 12:57:21.339153 2020] [wsgi:error] [pid 38988:tid 1324] [client 127.0.0.1:14622] Traceback (most recent call last):\r
[Sun Jan 12 12:57:21.339153 2020] [wsgi:error] [pid 38988:tid 1324] [client 127.0.0.1:14622]   File "E:/GitHub/clhcmdb/clhcmdb/wsgi.py", line 16, in <module>\r
[Sun Jan 12 12:57:21.339153 2020] [wsgi:error] [pid 38988:tid 1324] [client 127.0.0.1:14622]     application = get_wsgi_application()\r
[Sun Jan 12 12:57:21.339153 2020] [wsgi:error] [pid 38988:tid 1324] [client 127.0.0.1:14622]   File "c:\\users\\lee\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\django\\core\\wsgi.py", line 12, in get_wsgi_application\r
[Sun Jan 12 12:57:21.339153 2020] [wsgi:error] [pid 38988:tid 1324] [client 127.0.0.1:14622]     django.setup(set_prefix=False)\r
[Sun Jan 12 12:57:21.339153 2020] [wsgi:error] [pid 38988:tid 1324] [client 127.0.0.1:14622]   File "c:\\users\\lee\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\django\\__init__.py", line 24, in setup\r
[Sun Jan 12 12:57:21.339153 2020] [wsgi:error] [pid 38988:tid 1324] [client 127.0.0.1:14622]     apps.populate(settings.INSTALLED_APPS)\r
[Sun Jan 12 12:57:21.339153 2020] [wsgi:error] [pid 38988:tid 1324] [client 127.0.0.1:14622]   File "c:\\users\\lee\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\django\\apps\\registry.py", line 91, in populate\r
[Sun Jan 12 12:57:21.340153 2020] [wsgi:error] [pid 38988:tid 1324] [client 127.0.0.1:14622]     app_config = AppConfig.create(entry)\r
[Sun Jan 12 12:57:21.340153 2020] [wsgi:error] [pid 38988:tid 1324] [client 127.0.0.1:14622]   File "c:\\users\\lee\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\django\\apps\\config.py", line 90, in create\r
[Sun Jan 12 12:57:21.340153 2020] [wsgi:error] [pid 38988:tid 1324] [client 127.0.0.1:14622]     module = import_module(entry)\r
[Sun Jan 12 12:57:21.340153 2020] [wsgi:error] [pid 38988:tid 1324] [client 127.0.0.1:14622]   File "c:\\users\\lee\\appdata\\local\\programs\\python\\python36\\lib\\importlib\\__init__.py", line 126, in import_module\r
[Sun Jan 12 12:57:21.340153 2020] [wsgi:error] [pid 38988:tid 1324] [client 127.0.0.1:14622]     return _bootstrap._gcd_import(name[level:], package, level)\r
[Sun Jan 12 12:57:21.340153 2020] [wsgi:error] [pid 38988:tid 1324] [client 127.0.0.1:14622]   File "<frozen importlib._bootstrap>", line 994, in _gcd_import\r
[Sun Jan 12 12:57:21.340153 2020] [wsgi:error] [pid 38988:tid 1324] [client 127.0.0.1:14622]   File "<frozen importlib._bootstrap>", line 971, in _find_and_load\r
[Sun Jan 12 12:57:21.340153 2020] [wsgi:error] [pid 38988:tid 1324] [client 127.0.0.1:14622]   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked\r
[Sun Jan 12 12:57:21.340153 2020] [wsgi:error] [pid 38988:tid 1324] [client 127.0.0.1:14622] ModuleNotFoundError: No module named 'simpleui'\r
[Sun Jan 12 13:04:02.819170 2020] [mpm_winnt:notice] [pid 27784:tid 660] AH00424: Parent: Received restart signal -- Restarting the server.
[Sun Jan 12 13:04:02.898956 2020] [ssl:warn] [pid 27784:tid 660] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jan 12 13:04:02.898956 2020] [mpm_winnt:notice] [pid 27784:tid 660] AH00455: Apache/2.4.41 (Win64) OpenSSL/1.1.1c mod_wsgi/4.7.0 Python/3.6 configured -- resuming normal operations
[Sun Jan 12 13:04:02.899953 2020] [mpm_winnt:notice] [pid 27784:tid 660] AH00456: Server built: Aug 10 2019 13:33:27
[Sun Jan 12 13:04:02.899953 2020] [core:notice] [pid 27784:tid 660] AH00094: Command line: 'E:\\GitHub\\Apache24\\bin\\httpd.exe -d E:/GitHub/Apache24'
[Sun Jan 12 13:04:02.901948 2020] [mpm_winnt:notice] [pid 27784:tid 660] AH00418: Parent: Created child process 6920
[Sun Jan 12 13:04:03.324817 2020] [ssl:warn] [pid 6920:tid 616] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jan 12 13:04:03.360721 2020] [ssl:warn] [pid 6920:tid 616] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jan 12 13:04:03.820496 2020] [mpm_winnt:notice] [pid 6920:tid 616] AH00354: Child: Starting 64 worker threads.
[Sun Jan 12 13:04:04.820825 2020] [mpm_winnt:notice] [pid 38988:tid 592] AH00364: Child: All worker threads have exited.
[Sun Jan 12 13:04:08.576308 2020] [mpm_winnt:notice] [pid 27784:tid 660] AH00424: Parent: Received restart signal -- Restarting the server.
AH00526: Syntax error on line 190 of E:/GitHub/Apache24/conf/httpd.conf:
Listen requires 1 or 2 arguments.
[Sun Jan 12 13:04:10.578148 2020] [mpm_winnt:notice] [pid 6920:tid 616] AH00364: Child: All worker threads have exited.
[Sun Jan 12 13:36:36.711588 2020] [ssl:warn] [pid 39024:tid 644] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jan 12 13:36:36.792372 2020] [core:warn] [pid 39024:tid 644] AH00098: pid file E:/GitHub/Apache24/logs/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
[Sun Jan 12 13:36:36.795383 2020] [ssl:warn] [pid 39024:tid 644] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jan 12 13:36:36.796383 2020] [mpm_winnt:notice] [pid 39024:tid 644] AH00455: Apache/2.4.41 (Win64) OpenSSL/1.1.1c mod_wsgi/4.7.0 Python/3.6 configured -- resuming normal operations
[Sun Jan 12 13:36:36.809330 2020] [mpm_winnt:notice] [pid 39024:tid 644] AH00456: Server built: Aug 10 2019 13:33:27
[Sun Jan 12 13:36:36.809330 2020] [core:notice] [pid 39024:tid 644] AH00094: Command line: 'E:\\GitHub\\Apache24\\bin\\httpd.exe -d E:/GitHub/Apache24'
[Sun Jan 12 13:36:36.811351 2020] [mpm_winnt:notice] [pid 39024:tid 644] AH00418: Parent: Created child process 30240
[Sun Jan 12 13:36:37.255135 2020] [ssl:warn] [pid 30240:tid 664] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jan 12 13:36:37.305998 2020] [ssl:warn] [pid 30240:tid 664] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jan 12 13:36:37.395759 2020] [mpm_winnt:notice] [pid 30240:tid 664] AH00354: Child: Starting 64 worker threads.
[Sun Jan 12 13:36:46.986140 2020] [wsgi:error] [pid 30240:tid 1304] [client 127.0.0.1:5700] mod_wsgi (pid=30240): Failed to exec Python script file 'E:/GitHub/clhcmdb/clhcmdb/wsgi.py'.
[Sun Jan 12 13:36:46.986140 2020] [wsgi:error] [pid 30240:tid 1304] [client 127.0.0.1:5700] mod_wsgi (pid=30240): Exception occurred processing WSGI script 'E:/GitHub/clhcmdb/clhcmdb/wsgi.py'.
[Sun Jan 12 13:36:46.989106 2020] [wsgi:error] [pid 30240:tid 1304] [client 127.0.0.1:5700] Traceback (most recent call last):\r
[Sun Jan 12 13:36:46.990103 2020] [wsgi:error] [pid 30240:tid 1304] [client 127.0.0.1:5700]   File "E:/GitHub/clhcmdb/clhcmdb/wsgi.py", line 16, in <module>\r
[Sun Jan 12 13:36:46.990103 2020] [wsgi:error] [pid 30240:tid 1304] [client 127.0.0.1:5700]     application = get_wsgi_application()\r
[Sun Jan 12 13:36:46.990103 2020] [wsgi:error] [pid 30240:tid 1304] [client 127.0.0.1:5700]   File "c:\\users\\lee\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\django\\core\\wsgi.py", line 12, in get_wsgi_application\r
[Sun Jan 12 13:36:46.990103 2020] [wsgi:error] [pid 30240:tid 1304] [client 127.0.0.1:5700]     django.setup(set_prefix=False)\r
[Sun Jan 12 13:36:46.990103 2020] [wsgi:error] [pid 30240:tid 1304] [client 127.0.0.1:5700]   File "c:\\users\\lee\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\django\\__init__.py", line 24, in setup\r
[Sun Jan 12 13:36:46.990103 2020] [wsgi:error] [pid 30240:tid 1304] [client 127.0.0.1:5700]     apps.populate(settings.INSTALLED_APPS)\r
[Sun Jan 12 13:36:46.990103 2020] [wsgi:error] [pid 30240:tid 1304] [client 127.0.0.1:5700]   File "c:\\users\\lee\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\django\\apps\\registry.py", line 91, in populate\r
[Sun Jan 12 13:36:46.990103 2020] [wsgi:error] [pid 30240:tid 1304] [client 127.0.0.1:5700]     app_config = AppConfig.create(entry)\r
[Sun Jan 12 13:36:46.990103 2020] [wsgi:error] [pid 30240:tid 1304] [client 127.0.0.1:5700]   File "c:\\users\\lee\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\django\\apps\\config.py", line 90, in create\r
[Sun Jan 12 13:36:46.990103 2020] [wsgi:error] [pid 30240:tid 1304] [client 127.0.0.1:5700]     module = import_module(entry)\r
[Sun Jan 12 13:36:46.990103 2020] [wsgi:error] [pid 30240:tid 1304] [client 127.0.0.1:5700]   File "c:\\users\\lee\\appdata\\local\\programs\\python\\python36\\lib\\importlib\\__init__.py", line 126, in import_module\r
[Sun Jan 12 13:36:46.990103 2020] [wsgi:error] [pid 30240:tid 1304] [client 127.0.0.1:5700]     return _bootstrap._gcd_import(name[level:], package, level)\r
[Sun Jan 12 13:36:46.990103 2020] [wsgi:error] [pid 30240:tid 1304] [client 127.0.0.1:5700]   File "<frozen importlib._bootstrap>", line 994, in _gcd_import\r
[Sun Jan 12 13:36:46.990103 2020] [wsgi:error] [pid 30240:tid 1304] [client 127.0.0.1:5700]   File "<frozen importlib._bootstrap>", line 971, in _find_and_load\r
[Sun Jan 12 13:36:46.990103 2020] [wsgi:error] [pid 30240:tid 1304] [client 127.0.0.1:5700]   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked\r
[Sun Jan 12 13:36:46.990103 2020] [wsgi:error] [pid 30240:tid 1304] [client 127.0.0.1:5700] ModuleNotFoundError: No module named 'simpleui'\r
[Sun Jan 12 13:36:47.053933 2020] [wsgi:error] [pid 30240:tid 1304] [client 127.0.0.1:5702] mod_wsgi (pid=30240): Failed to exec Python script file 'E:/GitHub/clhcmdb/clhcmdb/wsgi.py'.
[Sun Jan 12 13:36:47.053933 2020] [wsgi:error] [pid 30240:tid 1304] [client 127.0.0.1:5702] mod_wsgi (pid=30240): Exception occurred processing WSGI script 'E:/GitHub/clhcmdb/clhcmdb/wsgi.py'.
[Sun Jan 12 13:36:47.054930 2020] [wsgi:error] [pid 30240:tid 1304] [client 127.0.0.1:5702] Traceback (most recent call last):\r
[Sun Jan 12 13:36:47.054930 2020] [wsgi:error] [pid 30240:tid 1304] [client 127.0.0.1:5702]   File "E:/GitHub/clhcmdb/clhcmdb/wsgi.py", line 16, in <module>\r
[Sun Jan 12 13:36:47.054930 2020] [wsgi:error] [pid 30240:tid 1304] [client 127.0.0.1:5702]     application = get_wsgi_application()\r
[Sun Jan 12 13:36:47.054930 2020] [wsgi:error] [pid 30240:tid 1304] [client 127.0.0.1:5702]   File "c:\\users\\lee\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\django\\core\\wsgi.py", line 12, in get_wsgi_application\r
[Sun Jan 12 13:36:47.054930 2020] [wsgi:error] [pid 30240:tid 1304] [client 127.0.0.1:5702]     django.setup(set_prefix=False)\r
[Sun Jan 12 13:36:47.054930 2020] [wsgi:error] [pid 30240:tid 1304] [client 127.0.0.1:5702]   File "c:\\users\\lee\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\django\\__init__.py", line 24, in setup\r
[Sun Jan 12 13:36:47.054930 2020] [wsgi:error] [pid 30240:tid 1304] [client 127.0.0.1:5702]     apps.populate(settings.INSTALLED_APPS)\r
[Sun Jan 12 13:36:47.054930 2020] [wsgi:error] [pid 30240:tid 1304] [client 127.0.0.1:5702]   File "c:\\users\\lee\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\django\\apps\\registry.py", line 83, in populate\r
[Sun Jan 12 13:36:47.054930 2020] [wsgi:error] [pid 30240:tid 1304] [client 127.0.0.1:5702]     raise RuntimeError("populate() isn't reentrant")\r
[Sun Jan 12 13:36:47.054930 2020] [wsgi:error] [pid 30240:tid 1304] [client 127.0.0.1:5702] RuntimeError: populate() isn't reentrant\r
[Sun Jan 12 14:02:01.997582 2020] [wsgi:error] [pid 30240:tid 1304] [client 127.0.0.1:7617] mod_wsgi (pid=30240): Failed to exec Python script file 'E:/GitHub/clhcmdb/clhcmdb/wsgi.py'.
[Sun Jan 12 14:02:01.997582 2020] [wsgi:error] [pid 30240:tid 1304] [client 127.0.0.1:7617] mod_wsgi (pid=30240): Exception occurred processing WSGI script 'E:/GitHub/clhcmdb/clhcmdb/wsgi.py'.
[Sun Jan 12 14:02:01.997582 2020] [wsgi:error] [pid 30240:tid 1304] [client 127.0.0.1:7617] Traceback (most recent call last):\r
[Sun Jan 12 14:02:01.997582 2020] [wsgi:error] [pid 30240:tid 1304] [client 127.0.0.1:7617]   File "E:/GitHub/clhcmdb/clhcmdb/wsgi.py", line 16, in <module>\r
[Sun Jan 12 14:02:01.997582 2020] [wsgi:error] [pid 30240:tid 1304] [client 127.0.0.1:7617]     application = get_wsgi_application()\r
[Sun Jan 12 14:02:01.997582 2020] [wsgi:error] [pid 30240:tid 1304] [client 127.0.0.1:7617]   File "c:\\users\\lee\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\django\\core\\wsgi.py", line 12, in get_wsgi_application\r
[Sun Jan 12 14:02:01.997582 2020] [wsgi:error] [pid 30240:tid 1304] [client 127.0.0.1:7617]     django.setup(set_prefix=False)\r
[Sun Jan 12 14:02:01.997582 2020] [wsgi:error] [pid 30240:tid 1304] [client 127.0.0.1:7617]   File "c:\\users\\lee\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\django\\__init__.py", line 24, in setup\r
[Sun Jan 12 14:02:01.997582 2020] [wsgi:error] [pid 30240:tid 1304] [client 127.0.0.1:7617]     apps.populate(settings.INSTALLED_APPS)\r
[Sun Jan 12 14:02:01.997582 2020] [wsgi:error] [pid 30240:tid 1304] [client 127.0.0.1:7617]   File "c:\\users\\lee\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\django\\apps\\registry.py", line 83, in populate\r
[Sun Jan 12 14:02:01.997582 2020] [wsgi:error] [pid 30240:tid 1304] [client 127.0.0.1:7617]     raise RuntimeError("populate() isn't reentrant")\r
[Sun Jan 12 14:02:01.997582 2020] [wsgi:error] [pid 30240:tid 1304] [client 127.0.0.1:7617] RuntimeError: populate() isn't reentrant\r
[Sun Jan 12 14:13:52.256253 2020] [mpm_winnt:notice] [pid 39024:tid 644] AH00422: Parent: Received shutdown signal -- Shutting down the server.
[Sun Jan 12 14:13:54.258898 2020] [mpm_winnt:notice] [pid 30240:tid 664] AH00364: Child: All worker threads have exited.
[Sun Jan 12 14:13:58.577349 2020] [mpm_winnt:notice] [pid 39024:tid 644] AH00430: Parent: Child process 30240 exited successfully.
Starting the 'apache2.4' service
The 'apache2.4' service is running.
sl:warn] [pid 40280:tid 524] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jan 12 16:38:19.630908 2020] [ssl:warn] [pid 40280:tid 524] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jan 12 16:38:19.630908 2020] [mpm_winnt:notice] [pid 40280:tid 524] AH00455: Apache/2.4.41 (Win64) OpenSSL/1.1.1c mod_wsgi/4.7.0 Python/3.6 configured -- resuming normal operations
[Sun Jan 12 16:38:19.636895 2020] [mpm_winnt:notice] [pid 40280:tid 524] AH00456: Server built: Aug 10 2019 13:33:27
[Sun Jan 12 16:38:19.636895 2020] [core:notice] [pid 40280:tid 524] AH00094: Command line: 'E:\\GitHub\\Apache24\\bin\\httpd.exe -d E:/GitHub/Apache24'
[Sun Jan 12 16:38:19.638891 2020] [mpm_winnt:notice] [pid 40280:tid 524] AH00418: Parent: Created child process 24320
[Sun Jan 12 16:38:20.099685 2020] [ssl:warn] [pid 24320:tid 544] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jan 12 16:38:20.146529 2020] [ssl:warn] [pid 24320:tid 544] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
Fatal Python error: Py_Initialize: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00004b04 (most recent call first):
[Sun Jan 12 16:38:23.662128 2020] [mpm_winnt:crit] [pid 40280:tid 524] AH00419: master_main: create child process failed. Exiting.
[Sun Jan 12 16:41:40.480077 2020] [ssl:warn] [pid 17892:tid 676] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jan 12 16:41:40.808174 2020] [ssl:warn] [pid 17892:tid 676] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jan 12 16:41:40.808174 2020] [mpm_winnt:notice] [pid 17892:tid 676] AH00455: Apache/2.4.41 (Win64) OpenSSL/1.1.1c mod_wsgi/4.7.0 Python/3.6 configured -- resuming normal operations
[Sun Jan 12 16:41:40.808174 2020] [mpm_winnt:notice] [pid 17892:tid 676] AH00456: Server built: Aug 10 2019 13:33:27
[Sun Jan 12 16:41:40.808174 2020] [core:notice] [pid 17892:tid 676] AH00094: Command line: 'E:\\GitHub\\Apache24\\bin\\httpd.exe -d E:/GitHub/Apache24'
[Sun Jan 12 16:41:40.810168 2020] [mpm_winnt:notice] [pid 17892:tid 676] AH00418: Parent: Created child process 828
[Sun Jan 12 16:41:41.255010 2020] [ssl:warn] [pid 828:tid 616] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jan 12 16:41:41.348729 2020] [ssl:warn] [pid 828:tid 616] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
Fatal Python error: Py_Initialize: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007a10 (most recent call first):
[Sun Jan 12 16:41:43.066136 2020] [mpm_winnt:crit] [pid 17892:tid 676] AH00419: master_main: create child process failed. Exiting.
Starting the 'apache2.4' service
The 'apache2.4' service is running.
sl:warn] [pid 37236:tid 672] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jan 12 16:41:52.194144 2020] [ssl:warn] [pid 37236:tid 672] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jan 12 16:41:52.195134 2020] [mpm_winnt:notice] [pid 37236:tid 672] AH00455: Apache/2.4.41 (Win64) OpenSSL/1.1.1c mod_wsgi/4.7.0 Python/3.6 configured -- resuming normal operations
[Sun Jan 12 16:41:52.195134 2020] [mpm_winnt:notice] [pid 37236:tid 672] AH00456: Server built: Aug 10 2019 13:33:27
[Sun Jan 12 16:41:52.195134 2020] [core:notice] [pid 37236:tid 672] AH00094: Command line: 'E:\\GitHub\\Apache24\\bin\\httpd.exe -d E:/GitHub/Apache24'
[Sun Jan 12 16:41:52.196134 2020] [mpm_winnt:notice] [pid 37236:tid 672] AH00418: Parent: Created child process 34416
[Sun Jan 12 16:41:52.630969 2020] [ssl:warn] [pid 34416:tid 640] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jan 12 16:41:52.677817 2020] [ssl:warn] [pid 34416:tid 640] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
Fatal Python error: Py_Initialize: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00000748 (most recent call first):
[Sun Jan 12 16:41:54.567762 2020] [mpm_winnt:crit] [pid 37236:tid 672] AH00419: master_main: create child process failed. Exiting.
[Sun Jan 12 16:42:23.475462 2020] [ssl:warn] [pid 21804:tid 668] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jan 12 16:42:23.561262 2020] [ssl:warn] [pid 21804:tid 668] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jan 12 16:42:23.562257 2020] [mpm_winnt:notice] [pid 21804:tid 668] AH00455: Apache/2.4.41 (Win64) OpenSSL/1.1.1c mod_wsgi/4.7.0 Python/3.6 configured -- resuming normal operations
[Sun Jan 12 16:42:23.562257 2020] [mpm_winnt:notice] [pid 21804:tid 668] AH00456: Server built: Aug 10 2019 13:33:27
[Sun Jan 12 16:42:23.562257 2020] [core:notice] [pid 21804:tid 668] AH00094: Command line: 'E:\\GitHub\\Apache24\\bin\\httpd.exe -d E:/GitHub/Apache24'
[Sun Jan 12 16:42:23.563228 2020] [mpm_winnt:notice] [pid 21804:tid 668] AH00418: Parent: Created child process 35720
[Sun Jan 12 16:42:24.033002 2020] [ssl:warn] [pid 35720:tid 608] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jan 12 16:42:24.085830 2020] [ssl:warn] [pid 35720:tid 608] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
Fatal Python error: Py_Initialize: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

Current thread 0x000048bc (most recent call first):
[Sun Jan 12 16:42:25.768359 2020] [mpm_winnt:crit] [pid 21804:tid 668] AH00419: master_main: create child process failed. Exiting.
[Sun Jan 12 16:42:49.600147 2020] [ssl:warn] [pid 14876:tid 672] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jan 12 16:42:49.671956 2020] [ssl:warn] [pid 14876:tid 672] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jan 12 16:42:49.672953 2020] [mpm_winnt:notice] [pid 14876:tid 672] AH00455: Apache/2.4.41 (Win64) OpenSSL/1.1.1c mod_wsgi/4.7.0 Python/3.6 configured -- resuming normal operations
[Sun Jan 12 16:42:49.672953 2020] [mpm_winnt:notice] [pid 14876:tid 672] AH00456: Server built: Aug 10 2019 13:33:27
[Sun Jan 12 16:42:49.672953 2020] [core:notice] [pid 14876:tid 672] AH00094: Command line: 'E:\\GitHub\\Apache24\\bin\\httpd.exe -d E:/GitHub/Apache24'
[Sun Jan 12 16:42:49.674947 2020] [mpm_winnt:notice] [pid 14876:tid 672] AH00418: Parent: Created child process 39060
[Sun Jan 12 16:42:50.088841 2020] [ssl:warn] [pid 39060:tid 572] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jan 12 16:42:50.129731 2020] [ssl:warn] [pid 39060:tid 572] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
Fatal Python error: Py_Initialize: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00006f14 (most recent call first):
[Sun Jan 12 16:42:52.402653 2020] [mpm_winnt:crit] [pid 14876:tid 672] AH00419: master_main: create child process failed. Exiting.
[Sun Jan 12 16:45:26.041237 2020] [ssl:warn] [pid 6772:tid 668] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jan 12 16:45:26.361382 2020] [ssl:warn] [pid 6772:tid 668] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jan 12 16:45:26.361382 2020] [mpm_winnt:notice] [pid 6772:tid 668] AH00455: Apache/2.4.41 (Win64) OpenSSL/1.1.1c mod_wsgi/4.7.0 Python/3.6 configured -- resuming normal operations
[Sun Jan 12 16:45:26.361382 2020] [mpm_winnt:notice] [pid 6772:tid 668] AH00456: Server built: Aug 10 2019 13:33:27
[Sun Jan 12 16:45:26.361382 2020] [core:notice] [pid 6772:tid 668] AH00094: Command line: 'E:\\GitHub\\Apache24\\bin\\httpd.exe -d E:/GitHub/Apache24'
[Sun Jan 12 16:45:26.363393 2020] [mpm_winnt:notice] [pid 6772:tid 668] AH00418: Parent: Created child process 39856
[Sun Jan 12 16:45:26.807189 2020] [ssl:warn] [pid 39856:tid 572] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jan 12 16:45:26.854064 2020] [ssl:warn] [pid 39856:tid 572] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
Fatal Python error: Py_Initialize: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007398 (most recent call first):
[Sun Jan 12 16:45:28.632310 2020] [mpm_winnt:crit] [pid 6772:tid 668] AH00419: master_main: create child process failed. Exiting.
[Sun Jan 12 16:47:03.234532 2020] [ssl:warn] [pid 19468:tid 668] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jan 12 16:47:03.559663 2020] [ssl:warn] [pid 19468:tid 668] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jan 12 16:47:03.560660 2020] [mpm_winnt:notice] [pid 19468:tid 668] AH00455: Apache/2.4.41 (Win64) OpenSSL/1.1.1c mod_wsgi/4.7.0 Python/3.6 configured -- resuming normal operations
[Sun Jan 12 16:47:03.560660 2020] [mpm_winnt:notice] [pid 19468:tid 668] AH00456: Server built: Aug 10 2019 13:33:27
[Sun Jan 12 16:47:03.560660 2020] [core:notice] [pid 19468:tid 668] AH00094: Command line: 'E:\\GitHub\\Apache24\\bin\\httpd.exe -d E:/GitHub/Apache24'
[Sun Jan 12 16:47:03.562655 2020] [mpm_winnt:notice] [pid 19468:tid 668] AH00418: Parent: Created child process 11956
[Sun Jan 12 16:47:04.018436 2020] [ssl:warn] [pid 11956:tid 568] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jan 12 16:47:04.064313 2020] [ssl:warn] [pid 11956:tid 568] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
Fatal Python error: Py_Initialize: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00008378 (most recent call first):
[Sun Jan 12 16:47:13.562914 2020] [mpm_winnt:crit] [pid 19468:tid 668] AH00419: master_main: create child process failed. Exiting.
